executors:
- name: executor1
  type: multi_threaded
  cores: [2, 5, 6]
  nodes:
  - name: node1_name
    subscribe: NONE
    publish: topic1
    payload: 256B
  - name: node2_name
    subscribe: topic1
    publish: topic2
    payload: 128B
  - name: node3_name
    subscribe: topic2
    publish: topic3
    payload: 128B
  - name: node4_name
    subscribe: topic3
    publish: topic4
    payload: 128B
# - name: executor2
#   type: single_threaded
#   cores: [3]
#   nodes:
#   - name: node1_name
#     subscribe: NONE
#     publish: topic1
#     payload: 128B
#   - name: node2_name
#     subscribe: topic1
#     publish: topic2
#     payload: 128B
#   - name: node3_name
#     subscribe: topic2
#     publish: topic3
#     payload: 128B
#   - name: node4_name
#     subscribe: topic3
#     publish: topic4
#     payload: 128B