executors:
- cores:
  - 1
  - 2
  name: executor1
  nodes:
  - name: node1
    payload: 40.00KB
    publish: topic1
    subscribe: NONE
  - name: node2
    payload: 40.00KB
    publish: topic2
    subscribe: topic1
  - name: node3
    payload: 40.00KB
    publish: NONE
    subscribe: topic2
  type: multi_threaded
