executors:
- cores:
  - 1
  name: executor1
  nodes:
  - name: node1
    payload: 10.00KB
    publish: topic1
    subscribe: NONE
  type: single_threaded
- cores:
  - 2
  name: executor2
  nodes:
  - name: node2
    payload: 10.00KB
    publish: NONE
    subscribe: topic1
  type: multi_threaded
