executor1:
  core: 1
  nrof_nodes: 5
  nodes:
    node1:
      name: node1_name
      subscribe: NONE
      publish: topic1
      payload: 128B
    node2:
      name: node2_name
      subscribe: topic1
      publish: topic2
      payload: 128B
    node3:
      name: node3_name
      subscribe: topic2
      publish: topic3
      payload: 128B
    node4:
      name: node4_name
      subscribe: topic3
      publish: topic4
      payload: 128B