/camera:
  ros__parameters:
    message_size: 1KB
/control:
  ros__parameters:
    message_size: 1KB
/fusion:
  ros__parameters:
    message_size: 1KB
/perception:
  ros__parameters:
    message_size: 1KB
/planning:
  ros__parameters:
    message_size: 1KB
